import { describe, expect, it } from "vitest";
import { parseCertificate, pemToDer, sha256Hex } from "../src/x509";
import ec from "./fixtures/ec.pem?raw";
import far from "./fixtures/far.pem?raw";
import real from "./fixtures/real.pem?raw";
import rsa from "./fixtures/rsa.pem?raw";
import v1 from "./fixtures/v1.pem?raw";

/**
 * Fixtures are frozen certificates, so their expiry is irrelevant here — the
 * parser only reads fields. Four are generated by openssl to pin specific DER
 * shapes (RSA vs ECC keys, UTCTime vs GeneralizedTime, v3 vs v1), and one is a
 * real certificate served by example.com. Every expectation below was taken
 * from `openssl x509 -noout -subject -issuer -dates -serial -fingerprint`.
 */
const PEM: Record<string, string> = { rsa, ec, far, v1, real };
const load = (name: string) => pemToDer(PEM[name]);
const info = (name: string) => parseCertificate(load(name));

describe("parseCertificate", () => {
  it("reads an RSA leaf: names, validity, serial, SANs", () => {
    expect(info("rsa")).toEqual({
      subjectCN: "probe.example.com",
      issuerCN: "netatlas Test Root R1",
      issuerO: "netatlas test CA",
      notBefore: "2026-08-27T15:00:45Z",
      notAfter: "2029-12-09T15:00:45Z",
      // The certificate also carries `IP:203.0.113.10`; only dNSName entries
      // belong in `sans`, everything else in the GeneralNames is skipped.
      sans: ["probe.example.com", "www.probe.example.com"],
      serial: "1ccfd948562872e53d59ef0d3e27c9bfff4a28ae",
    });
  });

  it("reads an ECC leaf, whose SubjectPublicKeyInfo is a different size", () => {
    const c = info("ec");
    expect(c.subjectCN).toBe("*.ecc.example.org");
    expect(c.issuerO).toBe("netatlas test CA");
    expect(c.sans).toEqual(["*.ecc.example.org", "ecc.example.org"]);
    expect(c.notAfter).toBe("2028-11-04T15:00:45Z");
  });

  it("decodes GeneralizedTime for dates past 2049", () => {
    // UTCTime cannot express 2050+, so DER switches encoding. Getting the
    // two-digit/four-digit year wrong silently reports a cert as long expired.
    expect(info("far").notAfter).toBe("2059-07-05T15:00:45Z");
    expect(info("far").notBefore).toBe("2026-08-27T15:00:45Z");
  });

  it("handles a v1 certificate, which has no [0] version tag and no extensions", () => {
    const c = info("v1");
    expect(c.subjectCN).toBe("*.ecc.example.org");
    expect(c.serial).toBe("1ccfd948562872e53d59ef0d3e27c9bfff4a28b1");
    expect(c.notAfter).toBe("2029-02-12T15:00:45Z");
    expect(c.sans).toEqual([]);
  });

  it("reads a certificate served by a real CA", () => {
    const c = info("real");
    expect(c.subjectCN).toBe("example.com");
    expect(c.issuerCN).toBe("Cloudflare TLS Issuing ECC CA 3");
    expect(c.issuerO).toBe("SSL Corporation");
    expect(c.sans).toEqual(["example.com", "*.example.com"]);
    expect(c.serial).toBe("0624d0ab311558780b7d5213b9631831");
    expect(c.notBefore).toBe("2026-07-29T22:10:08Z");
  });

  it("throws rather than inventing fields when the DER is truncated", () => {
    const der = load("rsa");
    expect(() => parseCertificate(der.subarray(0, 40))).toThrow(/truncated DER|bad DER length/);
    expect(() => parseCertificate(new Uint8Array([0x30]))).toThrow();
  });
});

describe("pemToDer", () => {
  it("ignores the armour and any line ending Atlas hands us", () => {
    // Atlas returns the certificate as one JSON string with embedded newlines;
    // whichever flavour they are, the DER underneath must come out identical.
    const pem = rsa;
    for (const variant of [pem.replace(/\n/g, "\r\n"), pem.replace(/\n/g, "\n\n"), pem.trim()]) {
      expect([...pemToDer(variant)]).toEqual([...pemToDer(pem)]);
    }
  });

  it("produces DER starting with a SEQUENCE", () => {
    expect(load("rsa")[0]).toBe(0x30);
  });
});

describe("sha256Hex", () => {
  it("matches `openssl x509 -fingerprint -sha256`", async () => {
    await expect(sha256Hex(load("rsa"))).resolves.toBe(
      "290af5a70d5e1aff2e6abed76ba57470d44667fd8535bfecdb6e34135d6875d5",
    );
    await expect(sha256Hex(load("real"))).resolves.toBe(
      "6153a96fd1a6ab7f4d438fc34932484299d0729d9140b3a126bb2f9c07b02200",
    );
  });
});
